-- AlterTable
ALTER TABLE `User`
  ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Incident`
  ADD COLUMN `status` ENUM('OPEN', 'RESOLVED') NOT NULL DEFAULT 'OPEN',
  ADD COLUMN `resolutionDetails` VARCHAR(191) NULL,
  ADD COLUMN `reportedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
